### ISSUE TITLE
Feature request: formatting numerical columns in a DETable

### ISSUE THREAD

**Issue by tomsing1** [iSEE/iSEEde#18]
By default, the DESeq2 or limma results include a lot of decimals. Is there a way to limit the number of significant digits?
(As a workaround, I am currently applying `signif()` to the result objects before they are embedded into the SummarizedExperiment.)

**Comment by kevinrue** [comment]
Note to self: check whether this feature request could be implemented in the virtual class `iSEE::Table`.

Reason: `DETable` extends `RowTable` which extends `Table`. No reason why other tables should not benefit of the functionality too.

**Comment by kevinrue** [comment]
Answering my previous comment:
Prototype suggests that as things stand, the feature request cannot be implemented at Table-level, but needs to be implemented in the `.generateTable` method for each concrete class.
https://github.com/iSEE/iSEE/pull/new/kra-iseede-18

**Comment by kevinrue** [comment]
Fixed by #32 

Though some additional documentation is needed (e.g. `panelDefaults()`)

**Comment by kevinrue** [comment]
Documentation needs fixed by #33
