### ISSUE TITLE
[BUG] link to iSEEde outdated

### ISSUE THREAD

**Issue by dominikburri** [iSEE/iSEEde#43]
Link to iSEEde bioconductor page not working. 
Should be replaced by latest release: https://doi.org/doi:10.18129/B9.bioc.iSEEde

**Comment by federicomarini** [comment]
Do you mean in the README? This might indeed be a detritus of us using `BiocStyle::Biocpkg("iSEEde")` in the Rmd README.
Actually, if the default behavior of this function is to include some information on the version, I would probably argue that this is not really the best way to keep this "automatically up to date".

A better way would be to use the "classic" `https://bioconductor.org/packages/[anypackage]`, including our `iSEEde`.
Or am I missing something @csoneson / @kevinrue ?

**Comment by kevinrue** [comment]
Indeed, please specify exactly which link you refer to. That'll help us diagnose the issue and adequate solution.

**Comment by federicomarini** [comment]
this is my guess

<img width="686" alt="image" src="https://github.com/user-attachments/assets/ee6ac603-738e-432d-b9f8-dd716d653ae9">

(see the bottom line with the link, which is "expectable" given the behavior of `BiocStyle::Biocpkg`)

**Comment by kevinrue** [comment]
Maybe we need to simply get rid of the Rmd version. I don't think it brings any real value here.

**Comment by federicomarini** [comment]
that'd be a shortcut. But I also think the BiocStyle function behavior is subpar if you think long-term reachability of the links

**Comment by csoneson** [comment]
I agree that we can just as well get rid of the Rmd and use https://bioconductor.org/packages/iSEEde/ directly. I do think that the behaviour of BiocStyle is sensible in many situations (where you want the link to point to the same version as where you're running the code) but for the README a non-versioned link means less maintenance work.

**Comment by dominikburri** [comment]
> Indeed, please specify exactly which link you refer to. That'll help us diagnose the issue and adequate solution.

Hi, sorry forgot to add that.
This one: https://bioconductor.org/packages/3.16/iSEEde
It is referenced multiple times in the README.md

**Comment by kevinrue** [comment]
funnily, I the consistent use of BiocStyle meant that _all_ the links to packages were outdated, all pointing to the same old release :)

**Comment by federicomarini** [comment]
yeah, basically the last time we re-rendered those Rmd files...
Could be sensible to have an option there, IMO
